apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  replicas: 2 # You can set the number of desired replicas
  selector:
    matchLabels:
      app: flaskapp
  template:
    metadata:
      labels:
        app: flaskapp
    spec:
      containers:
      - name: flask-app-container
        image: jayakumar123/srmdemo:flaskapp
        ports:
        - containerPort: 5000